flyway:
  enabled: true
  locations: classpath:db/migration
  schemas: epolicy

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/epolicy
    password: test
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true